AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    MBR - Instance backcup jobs
    
Globals:
  Function:
    Runtime: python3.6
    Timeout: 10

Resources:

    MyBackup:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: MBR/build/
            Handler: mbr.handler
            Runtime: python3.6

            Events:
                MyTimer:
                    Type: Schedule
                    Properties:
                        Schedule: cron(33 10 * * * *)
                        

Outputs:
    MyBackup:
      Description: "Function ARN"
      Value: !GetAtt MyBackup.Arn