AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    MBR - Instance backcup jobs
    
Globals:
  Function:
    Runtime: python3.6
    Timeout: 10

Resources:

    MyBackup:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./
            Handler: mbr.handler
            Runtime: python3.6

            Policies:
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - 'ec2:Describe*'
                            - 'ec2:DeleteSnapshot'
                            - 'ec2:ModifySnapshotAttribute'
                            - 'ec2:CreateTags'
                            - 'ec2:ResetSnapshotAttribute'
                            - 'ec2:CreateSnapshot'
                        Resource:
                            - '*'

                      - Effect: Allow
                        Action:
                            - 's3:ListAllMyBuckets'
                            - 's3:GetBucketLocation'
                        Resource:
                            - '*'
                      - Effect: Allow
                        Action:
                            - 's3:ListBucket'
                        Resource:
                            - 'arn:aws:s3:::bl2018backup'
                      - Effect: Allow
                        Action:
                            - 's3:PutObject'
                            - 's3:GetObject'
                            - 's3:DeleteObject'
                        Resource:
                            - 'arn:aws:s3:::bl2018backup/*'

            Events:
                MyTimer:
                    Type: Schedule
                    Properties:
                        Schedule: cron(55 10 * * ? *)
                        

Outputs:
    MyBackup:
      Description: "Function ARN"
      Value: !GetAtt MyBackup.Arn